[package]
name = "rust_udp_echo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4"] }
log = { version = "0.4.21" }
env_logger = { version = "0.11.3" }
clap = { version = "4.5.4", features = ["derive"] }
