# fly.toml app configuration file generated for rust-udp-echo on 2024-05-03T00:27:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rust-udp-echo'
primary_region = 'gru'

[build]

[[services]]
  internal_port = 2054
  protocol = "udp"

  [[services.ports]]
    port = "2054"

[[env]]
  RUST_LOG = "info"
  BIND_ADDR = "fly-global-services:2054"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
